services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  airflow-init:
    build:
      context: .
      dockerfile: DockerFile
    container_name: airflow-init
    depends_on:
      - db
    environment:
      AIRFLOW__DATABASE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      AIRFLOW__DATABASE__DAGS_FOLDER: /opt/airflow/dags
      PYTHONPATH: /opt/airflow/data_engine
    volumes:
      - ./dags:/opt/airflow/dags
      - .:/opt/airflow/data_engine
      - airflow_data:/opt/airflow
    command: >
      bash -c "airflow db migrate &&
               airflow connections create-default-connections"

  airflow-webserver:
    build:
      context: .
      dockerfile: DockerFile
    container_name: airflow-webserver
    restart: always
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__DATABASE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      AIRFLOW__DATABASE__DAGS_FOLDER: /opt/airflow/dags
      PYTHONPATH: /opt/airflow/data_engine
    volumes:
      - ./dags:/opt/airflow/dags
      - .:/opt/airflow/data_engine
      - airflow_data:/opt/airflow
    ports:
      - "8080:8080"
    command: ["airflow", "webserver"]

  airflow-scheduler:
    build:
      context: .
      dockerfile: DockerFile
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - airflow-init
      - airflow-webserver
    environment:
      AIRFLOW__DATABASE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      AIRFLOW__DATABASE__DAGS_FOLDER: /opt/airflow/dags
      PYTHONPATH: /opt/airflow/data_engine
    volumes:
      - ./dags:/opt/airflow/dags
      - .:/opt/airflow/data_engine
      - airflow_data:/opt/airflow
    command: ["airflow", "scheduler"]

  data-engine:
    build:
      context: .
      dockerfile: DockerFile
    container_name: data_engine
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      DATABENTO_API_KEY: ${DATABENTO_API_KEY}
    volumes:
      - .:/opt/airflow/data_engine
    depends_on:
      - db
    command: ["poetry", "run", "python", "-m", "data.main"]

volumes:
  db_data:
  airflow_data:
