site_name: "AlgoGators API Documentation"
nav:
  - Home: index.md
  - API Reference: api_reference.md

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("app.")

theme:
  name: material

markdown_extensions:
  - toc
  - admonition
  - codehilite
